### ISSUE TITLE
youtube icon on Mac MenuBar as Muse app in App Store

### ISSUE THREAD

**Issue by educastro11** [quanglam2807/webcatalog-apps#15]
Name:
URL:
Icon:
I've got WebCatalog app for MAC. Wonderful idea!
I did install youtube in it. I Loved.
I'd like to give a suggestion. What about putting a MenuBar icon where you could access this youtube app just as an app called Muse in Mac App Store ?

**Comment by quanglam2807** [comment]
Same as quanglam2807/webcatalog#257
